name: Test
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  cibuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: bundle install
      - run: ./script/test-markdown.sh
      - run: ./script/test-without-link-check.sh
      - run: ./script/check-new-links.sh
